---
- name: Update all packages
  dnf:
      name: "*"
      state: latest
      releasever: latest

- name: Add the Nginx repository
  template:
      src: nginx.repo.j2
      dest: /etc/yum.repos.d/nginx.repo

- name: Install Nginx from the nginx-stable repository
  dnf:
      name: nginx
      state: present
      enablerepo: nginx-stable
      disablerepo: "*"

- name: Backup the default Nginx configuration file
  command:
      cmd: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.org
      creates: /etc/nginx/conf.d/default.conf.org
      removes: /etc/nginx/conf.d/default.conf
  when: domain_name is defined

- name: Deploy Nginx configuration
  template:
      src: www.conf.j2
      dest: /etc/nginx/conf.d/www.conf
  when: domain_name is defined

- name: Enable and start Nginx
  systemd:
      name: nginx
      enabled: yes
      state: started

- name: Restart service nginx, in all cases
  systemd:
      name: nginx
      state: restarted
  changed_when: no
